java.runtime.version=21

#pour dire a Spring oot de lire les variables d'environnement sur Render
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuration pour PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#pour que la donnée evolue avecc les modifs
spring.jpa.hibernate.ddl-auto=update